version: "3.8"

services:
  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: flow_sign
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:
