version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flow_sign
    ports:
      - 5432:5432
    networks:
      - my_network
    volumes:
      - db:/var/lib/postgresql/data
networks:
  my_network:

volumes:
  db:
    driver: local
